# 构建 Jekyll 站点并将其部署到 GitHub Pages 的示例工作流程
姓名：名称：部署 Jekyll 并预安装 GitHub Pages 依赖项

on:
  # 在针对默认分支的推送上运行# Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # 允许您从“操作”选项卡手动运行此工作流程# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents:   内容： 阅读
  pages:   页数：写
  id-token:   id 令牌：写入

# 仅允许一项并发部署，跳过正在进行的运行和最新排队的运行之间的排队运行。
# 但是，不要取消正在进行的运行，因为我们希望完成这些生产部署。
并发：
  组：“页面”
  取消进行中：false

工作：
  # 构建作业
  建造者：
    运行：ubuntu-latest
    脚步：
      -姓名：结账
        用途：actions/checkout@v3
      -名称：设置页面
        用途：actions/configure-pages@v3
      -名称：使用 Jekyll 构建
        用途：actions/jekyll-build-pages@v1
        和：
          来源：./
          目的地：./_site
      -姓名：上传神器
        用途：actions/upload-pages-artifact@v2

  # 作业布置
  部署：
    环境：
      名称：github-pages
      网址：$ {   { steps.deployment.outputs.page_url }   }
    运行：ubuntu-latest
    需求：满足
    脚步：
      -姓名：到配置GitHub页面
        编号： 部署
        使用：actions/deploy-pages@v2
